/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    AForm: typeof import('ant-design-vue/es')['Form']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    HandoverInfo: typeof import('./src/components/info/handoverInfo.vue')['default']
    MeasureCardView: typeof import('./src/components/card/MeasureCardView.vue')['default']
    MeasureInfo: typeof import('./src/components/subview/measureInfo.vue')['default']
    MeasureView: typeof import('./src/components/MeasureView.vue')['default']
    OpenTab: typeof import('./src/components/subview/subTab/openTab.vue')['default']
    PersonEdit: typeof import('./src/components/edit/personEdit.vue')['default']
    ProjectCardView: typeof import('./src/components/card/ProjectCardView.vue')['default']
    ProjectView: typeof import('./src/components/ProjectView.vue')['default']
    RollerTab: typeof import('./src/components/subview/subTab/rollerTab.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchemeInfo: typeof import('./src/components/edit/info/schemeInfo.vue')['default']
    SchememInfo: typeof import('./src/components/info/schememInfo.vue')['default']
    SchemeTable: typeof import('./src/components/info/subTable/schemeTable.vue')['default']
    SendCardView: typeof import('./src/components/card/SendCardView.vue')['default']
    SendSheetView: typeof import('./src/components/SendSheetView.vue')['default']
    WorkCardView: typeof import('./src/components/card/WorkCardView.vue')['default']
    WorkComCardView: typeof import('./src/components/card/WorkComCardView.vue')['default']
    WorkComView: typeof import('./src/components/workComView.vue')['default']
    WorkEdit: typeof import('./src/components/edit/workEdit.vue')['default']
    workSend: typeof import('./src/components/subview/workSend.vue')['default']
    WorkSheetView: typeof import('./src/components/WorkSheetView.vue')['default']
    WriteCardView: typeof import('./src/components/card/WriteCardView.vue')['default']
    WriterInfo: typeof import('./src/components/subview/writerInfo.vue')['default']
    WriterTable: typeof import('./src/components/subview/tables/writerTable.vue')['default']
    WriteView: typeof import('./src/components/WriteView.vue')['default']
    workInfo: typeof import('./src/components/info/workInfo.vue')['default']
  }
}
