/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputGroup: typeof import('ant-design-vue/es')['InputGroup']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASpace: typeof import('ant-design-vue/es')['Space']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    CommissionCardView: typeof import('./src/components/card/CommissionCardView.vue')['default']
    CommissionInfo: typeof import('./src/components/subview/commissionInfo.vue')['default']
    CommissionView: typeof import('./src/components/CommissionView.vue')['default']
    HandoverInfo: typeof import('./src/components/subview/handoverInfo.vue')['default']
    MeasureCardView: typeof import('./src/components/card/MeasureCardView.vue')['default']
    MeasureInfo: typeof import('./src/components/subview/measureInfo.vue')['default']
    MeasureView: typeof import('./src/components/MeasureView.vue')['default']
    ProjectCardView: typeof import('./src/components/card/ProjectCardView.vue')['default']
    ProjectView: typeof import('./src/components/ProjectView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchememInfo: typeof import('./src/components/subview/schememInfo.vue')['default']
    SchemeTable: typeof import('./src/components/subview/subTable/schemeTable.vue')['default']
    UploadImg: typeof import('./src/components/edit/uploadImg.vue')['default']
    WorkCardView: typeof import('./src/components/card/WorkCardView.vue')['default']
    WorkEdit: typeof import('./src/components/edit/workEdit.vue')['default']
    WorkInfo: typeof import('./src/components/subview/workInfo.vue')['default']
    WorkSheetView: typeof import('./src/components/WorkSheetView.vue')['default']
    WriteCardView: typeof import('./src/components/card/WriteCardView.vue')['default']
    WriterInfo: typeof import('./src/components/subview/writerInfo.vue')['default']
    WriteView: typeof import('./src/components/WriteView.vue')['default']
  }
}
