/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AMenu: typeof import('ant-design-vue/es')['Menu']
    Customer: typeof import('./src/components/customer/customer.vue')['default']
    Foot: typeof import('./src/components/foot/foot.vue')['default']
    Project: typeof import('./src/components/project/project.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/sidebar/sidebar.vue')['default']
    Stage: typeof import('./src/components/stage/stage.vue')['default']
    User: typeof import('./src/components/user/user.vue')['default']
  }
}
