common:
  localFiles: E:\\AqaraUpload\\
  imgFiles: http://aqara.club/img/
  serviceUrl: http://aqara.club:8081

huoban:
  application_id: 1002449
  application_secret: 5F5aMmUtCBbhNM4ahhYeG1wMK4mstbsG85VpI9Qw
  userInfo: https://api.huoban.com/v2/ticket
  SearchInfo: https://api.huoban.com/v2/item/table/
  updateTable: https://api.huoban.com/v2/item/
  addInfo: https://api.huoban.com/v2/item/table/

baidu:
  key: agKsVR6GPw5eCCzGF5dhnkMoOF9sZGdi
  url: http://api.map.baidu.com/geocoder/v2/

server:
  port: 8082
  tomcat:
    uri-encoding: UTF-8
    max-http-form-post-size: 8096
  max-http-request-header-size: 8MB

logging:
  level:
    root: INFO
  file:
    name: yunqi.log
  charset:
    console: UTF-8

spring:
  datasource:
    # jdbc 连接基础配置
    url: jdbc:mysql://localhost:3306/yunqi
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    # password: smartHome@123
    password: 123456
    generate-unique-name: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  sql:
    init:
      platform: all
      encoding: UTF-8

mybatis:
  mapper-locations: classpath*:mapping/*.xml