common:
  localFiles: E:\\AqaraUpload\\
  imgFiles: http://aqara.club/img/
  serviceUrl: http://aqara.club:8081

huoban:
  application_id: 1002449
  application_secret: 5F5aMmUtCBbhNM4ahhYeG1wMK4mstbsG85VpI9Qw
  userInfo: https://api.huoban.com/v2/ticket
  SearchInfo: https://api.huoban.com/v2/item/table/
  updateTable: https://api.huoban.com/v2/item/
  addInfo: https://api.huoban.com/v2/item/table/

baidu:
  key: agKsVR6GPw5eCCzGF5dhnkMoOF9sZGdi
  url: http://api.map.baidu.com/geocoder/v2/

server:
  port: 8082
  tomcat:
    uri-encoding: UTF-8
    max-http-form-post-size: 8096
  max-http-request-header-size: 8MB
  ssl:
    enabled: true
    key-store: classpath:aqara.club.jks
    # SSL证书密码 (自己在腾讯云申请证书时的密码，如果当时没填那么在压缩文件就会有一个txt文件存放密码)
    key-store-password: 89hr3k4t4ejemqc
    # 证书类型
    key-store-type: JKS

logging:
  level:
    root: INFO
  file:
    name: yunqi.log
  charset:
    console: UTF-8

spring:
  datasource:
    # jdbc 连接基础配置
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/yunqi
#    username: root
#    password: smartHome@123
    url: jdbc:mysql://1.116.43.244:3306/yunqi
    username: yunqi
    password: smartHome@123
    generate-unique-name: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 300MB
  sql:
    init:
      platform: all
      encoding: UTF-8

mybatis:
  mapper-locations: classpath*:mapping/*.xml