wx:
  corpId: ww9a717b03b06063e3
  corpSecret: nZv_TArU4E_PavzhhU22B6LJtT-BjaRmDCGjE64v0xQ
  corpHttp: http://aqara.club:8081
  httpUrl: https://qyapi.weixin.qq.com/cgi-bin/gettoken
  userIdUrl: https://qyapi.weixin.qq.com/cgi-bin/user/getuserinfo
  jsapiUrl: https://qyapi.weixin.qq.com/cgi-bin/get_jsapi_ticket
  appUrl: https://qyapi.weixin.qq.com/cgi-bin/ticket/get
  externalContact: https://qyapi.weixin.qq.com/cgi-bin/externalcontact/get
  externalList: https://qyapi.weixin.qq.com/cgi-bin/externalcontact/list
  groupChat: https://qyapi.weixin.qq.com/cgi-bin/externalcontact/groupchat/get
  groupList: https://qyapi.weixin.qq.com/cgi-bin/externalcontact/groupchat/list
  permitList: https://qyapi.weixin.qq.com/cgi-bin/msgaudit/get_permit_user_list
  checkAgree: https://qyapi.weixin.qq.com/cgi-bin/msgaudit/check_single_agree
  calendarAdd: https://qyapi.weixin.qq.com/cgi-bin/oa/calendar/add
  scheduleAdd: https://qyapi.weixin.qq.com/cgi-bin/oa/schedule/add
  mediaUpload: https://qyapi.weixin.qq.com/cgi-bin/media/upload
  compUser: https://qyapi.weixin.qq.com/cgi-bin/user/get

qy:
  SuiteID: ww2fd0def5ad11e2cf
  Secret: aVnpGsZAPvWpRsZvyliB8qiXbZhkeGzvJdSv4OP14H0
  CorpID: ww9a717b03b06063e3
  ProviderSecret: hC2cKE9D2d_D4gXwpNMcSxp49T95UQz7YVSUaV4xC0DUoqwBoJ5jKhvtv8SCFEdX
  token: 9IoF
  encodingAESKey: cg5DROA8wox9A5F8cFrM4GTVOuTaH45K5IXT4v31D7v
  authorize: https://open.weixin.qq.com/connect/oauth2/authorize
  preAuthCode: https://qyapi.weixin.qq.com/cgi-bin/service/get_pre_auth_code
  provider_token: https://qyapi.weixin.qq.com/cgi-bin/service/get_provider_token
  suite_token: https://qyapi.weixin.qq.com/cgi-bin/service/get_suite_token
  session_info: https://qyapi.weixin.qq.com/cgi-bin/service/set_session_info
  permanent_code: https://qyapi.weixin.qq.com/cgi-bin/service/get_permanent_code
  corp_token: https://qyapi.weixin.qq.com/cgi-bin/service/get_corp_token
  get_permissions: https://qyapi.weixin.qq.com/cgi-bin/agent/get_permissions
  jsapiTicket: https://qyapi.weixin.qq.com/cgi-bin/get_jsapi_ticket
  AppTicket: https://qyapi.weixin.qq.com/cgi-bin/ticket/get
  externalContact: https://qyapi.weixin.qq.com/cgi-bin/externalcontact/get

program:
  code2Session: https://api.weixin.qq.com/sns/jscode2session
  phoneNumber: https://api:weixin:qq:com/wxa/business/getuserphonenumber
  accessToken: https://api.weixin.qq.com/cgi-bin/token
  appid: wxa364df767870a7d5
  secret: 21b5fef5e9259d320826fde8e0375b92aaa

common:
  localFiles: E:\\AqaraUpload\\
  imgFiles: http://aqara.club/img/
  serviceUrl: http://aqara.club:8081

huoban:
  application_id: 1002449
  application_secret: 5F5aMmUtCBbhNM4ahhYeG1wMK4mstbsG85VpI9Qw
  userInfo: https://api.huoban.com/v2/ticket
  SearchInfo: https://api.huoban.com/v2/item/table/
  updateTable: https://api.huoban.com/v2/item/
  addInfo: https://api.huoban.com/v2/item/table/

reboot:
  customerBroadcast: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=283f104b-f171-41a0-a7cc-fd977884330c
  projectBroadcast: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=0adf9002-d736-4921-b35f-f36c6429b097

baidu:
  key: agKsVR6GPw5eCCzGF5dhnkMoOF9sZGdi
  url: http://api.map.baidu.com/geocoder/v2/

server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
    max-http-form-post-size: 8096
  max-http-request-header-size: 16MB

logging:
  level:
    root: INFO
  file:
    name: aqara.log
  charset:
    console: UTF-8

spring:
  datasource:
    # jdbc 连接基础配置
    url: jdbc:mysql://localhost:3306/aqara
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: smartHome@123
    generate-unique-name: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  sql:
    init:
      platform: all
      encoding: UTF-8

mybatis:
  mapper-locations: classpath*:mapping/*.xml