
  # 开发者应该设置成自己的wx相关信息
  # corpId: ww728dd07f7641e567
  # corpSecret: gI7rD-tDe6i47qzxuNc7xG7M4gUURgKOPWYY6QOAro4
wx:
  corpId: ww9a717b03b06063e3
  corpSecret: nZv_TArU4E_PavzhhU22B6LJtT-BjaRmDCGjE64v0xQ
  sessionSecret: F7lF9dM986yTDpAKlhN-CndaBA1OxCAL4j9EKZVtjbA
  httpUrl: https://qyapi.weixin.qq.com/cgi-bin/gettoken
  userIdUrl: https://qyapi.weixin.qq.com/cgi-bin/user/getuserinfo
  jsapiUrl: https://qyapi.weixin.qq.com/cgi-bin/get_jsapi_ticket
  appUrl: https://qyapi.weixin.qq.com/cgi-bin/ticket/get
  externalcontact: https://qyapi.weixin.qq.com/cgi-bin/externalcontact/get
  externalList: https://qyapi.weixin.qq.com/cgi-bin/externalcontact/list
  groupchat: https://qyapi.weixin.qq.com/cgi-bin/externalcontact/groupchat/get
  groupList: https://qyapi.weixin.qq.com/cgi-bin/externalcontact/groupchat/list
  permitlist: https://qyapi.weixin.qq.com/cgi-bin/msgaudit/get_permit_user_list
  checkAgree: https://qyapi.weixin.qq.com/cgi-bin/msgaudit/check_single_agree
    
huoban:
  application_id: 1002449
  application_secret: 5F5aMmUtCBbhNM4ahhYeG1wMK4mstbsG85VpI9Qw
  ticket: IXvB6iAouWyAwLr9W4Macgk1ajsxxfmPd4QqkKK2
  expired: 1209600
  userInfo: https://api.huoban.com/v2/ticket
  SearchInfo: https://api.huoban.com/v2/item/table/
  updateTable: https://api.huoban.com/v2/item/
  addInfo: https://api.huoban.com/v2/item/table/
  
reboot:
  customerBroadcast: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=283f104b-f171-41a0-a7cc-fd977884330c
  projectBroadcast: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=0adf9002-d736-4921-b35f-f36c6429b097
  
baidu:
  key: agKsVR6GPw5eCCzGF5dhnkMoOF9sZGdi
  url: http://api.map.baidu.com/geocoder/v2/
  
server:
  #port: 8091
  port: 8081
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    # jdbc 连接基础配置
    url: jdbc:mysql://localhost:3306/aqara
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    sql-script-encoding: UTF-8
    data-username: 
    data-password: 
    generate-unique-name: false
    platform: all

mybatis:
  mapper-locations: classpath*:mapping/*.xml